name: Python package

on:
  push:
    branches: master
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Lint Python
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v3


  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip "setuptools<46" wheel
        pip install tox tox-gh-actions
    - name: Test with tox
      run: |
        tox
